//USER INPUT START
export const CHANGE_PAGE = "CHANGE_PAGE";
export const UPDATE_PREFS = "UPDATE_PREFS";
export const CHANGE_PLAN_TYPE = "CHANGE_PLAN_TYPE";
export const UPDATE_TEXT_RESPONSE = "UPDATE_TEXT_RESPONSE";
export const RESET_RESPONSES = "RESET_RESPONSES";
export const UPDATE_PLANS = "UPDATE_PLANS";
export const UPDATE_SORT_ORDER = "UPDATE_SORT_ORDER";
export const UPDATE_PRICE = "UPDATE_PRICE";
export const FILTER_LOCATIONS = "FILTER_LOCATIONS";
export const UPDATE_BEST_PLAN = "UPDATE_BEST_PLAN";
export const UPDATE_CHEAPEST_PLAN = "UPDATE_CHEAPEST_PLAN";
export const UPDATE_MOSTEXPENSIVE_PLAN = "UPDATE_MOSTEXPENSIVE_PLAN";
export const UPDATE_NOTGETTINGPROVIDERS = "UPDATE_NOTGETTINGPROVIDERS";
export const UPDATE_BUDGET = "UPDATE_BUDGET";
export const TOGGLE_FAMILY_PLAN_SELECTED = "TOGGLE_FAMILY_PLAN_SELECTED";
export const UPDATE_COVERS = "UPDATE_COVERS";
export const TOGGLE_BUYING_PLAN = "TOGGLE_BUYING_PLAN";
export const RESET_PLANS = "RESET_PLANS";
export const TOGGLE_DESKTOP_MODAL = "TOGGLE_DESKTOP_MODAL";
export const TOGGLE_MOBILE_MODAL = "TOGGLE_MOBILE_MODAL";
export const TOGGLE_OTHERS_MODAL = "TOGGLE_OTHERS_MODAL";
export const UPDATE_GENDER = "UPDATE_GENDER";
export const UPDATE_TYPE = "UPDATE_TYPE";
export const TOGGLE_DESKTOP_VIEW = "TOGGLE_DESKTOP_VIEW";
export const UPDATE_PHONE = "UPDATE_PHONE";
export const UPDATE_FULL_NAME = "UPDATE_FULL_NAME";
export const UPDATE_INDIVIDUAL_AGE = "UPDATE_INDIVIDUAL_AGE";
export const UPDATE_FATHER_AGE = "UPDATE_FATHER_AGE";
export const UPDATE_MOTHER_AGE = "UPDATE_MOTHER_AGE";
export const UPDATE_GRAND_FATHER_AGE = "UPDATE_GRAND_FATHER_AGE";
export const UPDATE_GRAND_MOTHER_AGE = "UPDATE_GRAND_MOTHER_AGE";
export const UPDATE_FATHER_IN_LAW_AGE = "UPDATE_FATHER_IN_LAW_AGE";
export const UPDATE_MOTHER_IN_LAW_AGE = "UPDATE_MOTHER_IN_LAW_AGE";
export const UPDATE_SPOUSE_AGE = "UPDATE_SPOUSE_AGE";
export const UPDATE_CHILD_1_AGE = "UPDATE_CHILD_1_AGE";
export const UPDATE_CHILD_2_AGE = "UPDATE_CHILD_2_AGE";
export const UPDATE_CHILD_3_AGE = "UPDATE_CHILD_3_AGE";
export const UPDATE_CHILD_4_AGE = "UPDATE_CHILD_4_AGE";
export const UPDATE_CHILD_5_AGE = "UPDATE_CHILD_5_AGE";
export const UPDATE_CHILD_6_AGE = "UPDATE_CHILD_6_AGE";
export const UPDATE_CHILD_7_AGE = "UPDATE_CHILD_7_AGE";
export const UPDATE_CHILD_8_AGE = "UPDATE_CHILD_8_AGE";
export const UPDATE_SON_CHECKED = "UPDATE_SON_CHECKED";
export const UPDATE_DAUGHTER_CHECKED = "UPDATE_DAUGHTER_CHECKED";
export const INCREMENT_SON_COUNT = "INCREMENT_SON_COUNT";
export const DECREMENT_SON_COUNT = "DECREMENT_SON_COUNT";
export const INCREMENT_DAUGHTER_COUNT = "INCREMENT_DAUGHTER_COUNT";
export const DECREMENT_DAUGHTER_COUNT = "DECREMENT_DAUGHTER_COUNT";
export const UPDATE_PLAN_DURATION = "UPDATE_PLAN_DURATION";
export const TOGGLE_FEATURES_MODAL = "TOGGLE_FEATURES_MODAL";
export const UPDATE_FEATURES_TAB_OPENED = "UPDATE_FEATURES_TAB_OPENED";
export const TOGGLE_FEATURE_POPUP = "TOGGLE_FEATURE_POPUP";
export const RESET_TYPE = "RESET_TYPE";
export const RESET_BUDGET = "RESET_BUDGET";
export const RESET_RANGE = "RESET_RANGE"
export const SET_PROVIDERS = "SET_PROVIDERS"
export const RESET_SELECTED_PROVIDERS = "RESET_SELECTED_PROVIDERS"
export const ADD_COMPARE_URL_PARAM = "ADD_COMPARE_URL_PARAM";
export const REMOVE_COMPARE_URL_PARAM = "REMOVE_COMPARE_URL_PARAM";
export const TOGGLE_DATA_CAPTURE_MODAL = "TOGGLE_DATA_CAPTURE_MODAL"

//USER INPUT END

//DATA FETCH START
export const GET_PLANS = "GET_PLANS";
export const GET_HMOS = "GET_HMOS";
export const GET_SERVICES = "GET_SERVICES";
export const GET_PROVIDERS = "GET_PROVIDERS";
export const GET_RECOMMENDED_PLANS = "GET_RECOMMENDED_PLANS";
export const GET_CLICKED_PLAN = "GET_CLICKED_PLAN";
export const GET_DOCTORS = "GET_DOCTORS";

export const IS_FETCHING_PLANS = "IS_FETCHING_PLANS";
export const IS_FETCHING_HMOS = "IS_FETCHING_HMOS";
export const IS_FETCHING_SERVICES = "IS_FETCHING_SERVICES";
export const IS_FETCHING_PROVIDERS = "IS_FETCHING_PROVIDERS";
export const IS_FETCHING_RECOMMENDED_PLANS = "IS_FETCHING_RECOMMENDED_PLANS";

export const UPDATE_NUM_OF_PEOPLE = "UPDATE_NUM_OF_PEOPLE";
export const RESET_NUM_OF_PEOPLE = "RESET_NUM_OF_PEOPLE";
export const GET_NUM_OF_PEOPLE = "GET_NUM_OF_PEOPLE";

export const GET_CHEAPEST_PLAN = "GET_CHEAPEST_PLAN";
export const GET_CHEAPEST_PLAN_BY_HMO = "GET_CHEAPEST_PLAN_BY_HMO";
export const GET_PLANS_BY_HMO = "GET_PLANS_BY_HMO";
export const IS_FETCHING_PLANS_BY_HMO = "IS_FETCHING_PLANS_BY_HMO";
export const GET_PROVIDER_INFO = "GET_PROVIDER_INFO";

export const GET_PLAN = "GET_PLAN";
export const GET_SIMILAR_PLANS = "GET_SIMILAR_PLANS";
//DATA FETCH END

//COMPARE START
export const SET_PLANS_TO_COMPARE_ON_DESKTOP =
    "SET_PLANS_TO_COMPARE_ON_DESKTOP";
export const SET_PLANS_TO_COMPARE_ON_MOBILE = "SET_PLANS_TO_COMPARE_ON_MOBILE";
export const SET_CHECKED_PLANS = "SET_CHECKED_PLANS";
//COMPARE END

// FILTER BEGIN
export const FORMAT_PRICES = "FORMAT_PRICES";
export const UPDATE_PRICE_RANGE = "UPDATE_PRICE_RANGE";
export const FILTER_PROVIDERS = "FILTER_PROVIDERS";
export const FILTER_PRESCRIPTIONS = "FILTER_PRESCRIPTIONS";
export const UPDATE_SELECTED_PROVIDERS = "UPDATE_SELECTED_PROVIDERS";
//FILTER END

//AUTH BEGIN
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
//AUTH END

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ERRORS = "GET_ERRORS";

export const FILTER_BY_BUDGET = "FILTER_BY_BUDGET"
export const FILTER_BY_HMO = "FILTER_BY_HMO";
export const FILTER_BY_PLAN_ID = "FILTER_BY_PLAN_ID";
export const FILTER_BY_PLAN_TYPE = "FILTER_BY_PLAN_TYPE"
export const FILTER_BY_PLAN_RANGE = "FILTER_BY_PLAN_RANGE"

export const FILTER_BY_TOTAL_BENEFIT_LIMIT = "FILTER_BY_TOTAL_BENEFIT_LIMIT";
export const FILTER_BY_BENEFITS = "FILTER_BY_BENEFITS";
export const FILTER_BY_DOCTOR = "FILTER_BY_DOCTOR";
export const FILTER_BY_PROXIMITY = "FILTER_BY_PROXIMITY";

export const IS_FILTERING_BY_BUDGET = "IS_FILTERING_BY_BUDGET"
export const IS_FILTERING_BY_PLAN_TYPE = "IS_FILTERING_BY_PLAN_TYPE"
export const IS_FILTERING_BY_PLAN_RANGE = "IS_FILTERING_BY_PLAN_RANGE"
export const IS_FILTERING_BY_PLAN_ID = "IS_FILTERING_BY_PLAN_ID";

export const SET_PLAN_ID = "SET_PLAN_ID";
export const SET_HMO_ID = "SET_HMO_ID";

export const SET_IS_LOADING_ON = "SET_IS_LOADING_ON";
export const SET_IS_LOADING_OFF = "SET_IS_LOADING_OFF";

export const GET_HMO = "GET_HMO";

export const TOGGLE_PLAN_PROVIDERS = "TOGGLE_PLAN_PROVIDERS";

export const UPDATE_INFINITE_SCROLL_DATA = "UPDATE_INFINITE_SCROLL_DATA";
export const SET_IS_INFINNITE_SCROLL_HAS_MORE = "SET_IS_INFINNITE_SCROLL_HAS_MORE";
export const RESET_INFINITE_SCROLL_DATA = "RESET_INFINITE_SCROLL_DATA";

//export const IS_FILTERING_BY_HMO = "IS_FILTERING_BY_HMO";

export const SET_DOCTORS = "SET_DOCTORS";
export const SET_BENEFITS = "SET_BENEFITS";
export const FILTER_BENEFITS = "FILTER_BENEFITS";
export const FILTER_DOCTORS = "FILTER_DOCTORS";


export const TOGGLE_FILTER_BOX = "TOGGLE_FILTER_BOX";

export const GET_SPECIALTIES = "GET_SPECIALTIES";
export const SET_LOCATION = "SET_LOCATION";

export const HANDLE_GEOCODING = "HANDLE_GEOCODING";
export const HANDLE_REVERSE_GEOCODING = "HANDLE_REVERSE_GEOCODING";

export const COMPARE_TOP_THREE_PLANS = "COMPARE_TOP_THREE_PLANS";
export const GET_TOP_THREE_PLANS = "GET_TOP_THREE_PLANS";

export const RESET_SELECTED_DOCTOR = "RESET_SELECTED_DOCTOR";
export const RESET_BENEFITS = "RESET_BENEFITS";
export const RESET_LOCATION = "RESET_LOCATION";
export const RESET_PLAN_ID = "RESET_PLAN_ID";

export const HANDLE_PLAN_RANGE_CHECK = "HANDLE_PLAN_RANGE_CHECK"
export const HANDLE_PLAN_TYPES_CHECK = "HANDLE_PLAN_TYPES_CHECK"
export const HANDLE_PROVIDER_SELECTED = "HANDLE_PROVIDER_SELECTED"
export const HANDLE_PRESCRIPTION_SELECTED = "HANDLE_PRESCRIPTION_SELECTED"
export const HANDLE_MIN_RANGE_CHANGE = "HANDLE_MIN_RANGE_CHANGE"
export const HANDLE_MAX_RANGE_CHANGE = "HANDLE_MAX_RANGE_CHANGE"
export const HANDLE_TOTAL_BENEFIT_MIN_CHANGE = "HANDLE_TOTAL_BENEFIT_MIN_CHANGE"
export const HANDLE_TOTAL_BENEFIT_MAX_CHANGE = "HANDLE_TOTAL_BENEFIT_MAX_CHANGE"
export const HANDLE_PLAN_ID_CHANGE = "HANDLE_PLAN_ID_CHANGE"
export const ENABLE_SEARCH_BY_PROXIMITY = "ENABLE_SEARCH_BY_PROXIMITY"
export const HANDLE_MIN_DED_CHANGE = "HANDLE_MIN_DED_CHANGE"
export const HANDLE_MAX_DED_CHANGE = "HANDLE_MAX_DED_CHANGE"
export const HANDLE_HMO_SELECTED = "HANDLE_HMO_SELECTED"
export const RESET_FILTER_PARAMS = "RESET_FILTER_PARAMS"
export const SET_COORDINATES_AND_ADDRESS = "SET_COORDINATES_AND_ADDRESS"
export const HANDLE_ADDRESS_IMPUT = "HANDLE_ADDRESS_IMPUT"
export const CLEAR_DOCTORS_FILTER = "CLEAR_DOCTORS_FILTER"
export const CLEAR_PROVIDERS_FILTER = "CLEAR_PROVIDERS_FILTER"
export const CLEAR_BUDGET_FILTER = "CLEAR_BUDGET_FILTER"
export const CLEAR_PLAN_TYPE_FILTER = "CLEAR_PLAN_TYPE_FILTER"
export const CLEAR_PLAN_METAL_LEVEL_FILTER = "CLEAR_PLAN_METAL_LEVEL_FILTER"
export const CLEAR_PLAN_ID_FILTER = "CLEAR_PLAN_ID_FILTER"
export const CLEAR_HMO_ID_FILTER = "CLEAR_HMO_ID_FILTER"
export const CLEAR_PROXIMITY_FILTER = "CLEAR_PROXIMITY_FILTER"
export const CLEAR_BENEFITS_FILTER = "CLEAR_BENEFITS_FILTER"
export const CLEAR_TOTAL_BENEFIT_RANGE_FILTER = "CLEAR_TOTAL_BENEFIT_RANGE_FILTER"
export const UPDATE_APPLIED_FILTERS = "UPDATE_APPLIED_FILTERS"

export const TOGGLE_JUMP_TO_FILTER_BOX = "TOGGLE_JUMP_TO_FILTER_BOX";

export const IS_FETCHING_DATA = "IS_FETCHING_DATA";