export const state: any = {
  quiz: {
    page: 2,
    minPage: 1,
    maxPage: 4,
    checked: [],
    dataSource: [],
    didRequestReturnEmptyResult: false,
    familyPlanSelected: false,
    covers: "",
    isOpen: false,
    isMobileViewModalOpen: false,
    isOthersInputOpen: false,
    isFeaturesModalOpen: false,
    isFeaturePopUpOpen: false,
    isDesktopView: true,
    isSonCheckboxChecked: false,
    isDaughterCheckboxChecked: false,
    sonCount: 1,
    daughterCount: 1,
    tab_opened: "highlights",

    responses: {
      budget: [20000, 80000],
      num_of_people: 1,
      type: "single",
      firstName: "",
      lastName: "",
      email: "",
      state: "",
      adult: 1,
      children: 0,
      infants: 0,
      // services: {
      //   cancerCare: false,
      //   physiotherapy: false,
      //   psychiatricTreatment: false,
      //   familyPlanningServices: false,
      //   mortuaryServices: false,
      //   natalCare: false,
      //   dentalOptions: false,
      //   opticalOptions: false,
      //   diagnostics: false,
      // },
      gender: "m",
      full_name: "",
      phone_num: "",
      individual_age: 19,
      father_age: 0,
      mother_age: 0,
      grand_father_age: 0,
      grand_mother_age: 0,
      father_in_law_age: 0,
      mother_in_law_age: 0,
      spouse_age: 0,
      child_1_age: 0,
      child_2_age: 0,
      child_3_age: 0,
      child_4_age: 0,
      child_5_age: 0,
      child_6_age: 0,
      child_7_age: 0,
      child_8_age: 0,
      plan_duration: "1",
      price_range: "medium",
    },
  },
  compare: {
    fetching: false,
    plans: [],
    sort: {
      mode: "desc",
      icon: "sort-ascending",
      description: "Sort by price (most expensive first)",
    },
    bestPlan: {},
    cheapestPlan: {},
    mostExpensivePlan: {},
  },
  details: {
    email: "",
    price: 0,
    notGettingProviders: true,
    buyingPlan: false,
  },
  plans: [],
  recommended_plans: [],
  clicked_plan: [],
  hmos: [],
  services: [],
  providers: [],
  fetching_plans: false,
  fetching_hmos: false,
  fetching_services: false,
  fetching_providers: false,
  fetching_recommended_plans: false,
  compare_plans_mobile_indexes: [],
  compare_plans_desktop_indexes: [],
  checked_plans_list: [],
  cheapest_plan_by_hmo: 0,
  cheapest_plan: 0,
  provider_plans: [],
  filter_plans_by_hmo: false,
  provider_info: [],
};
