export const state: any = {
  quiz: {
    page: 2,
    minPage: 1,
    maxPage: 4,
    checked: [],
    dataSource: [],
    didRequestReturnEmptyResult: false,
    familyPlanSelected: false,
    covers: "",
    isOpen: false,
    isMobileViewModalOpen: false,
    isOthersInputOpen: false,
    numOfPersons: "parents",
    isDesktopView: true,
    gender: "m",

    responses: {
      budget: [300000, 350000],
      type: "parents",
      firstName: "",
      lastName: "",
      email: "",
      state: "",
      adult: 1,
      children: 0,
      infants: 0,
      services: {
        cancerCare: false,
        physiotherapy: false,
        psychiatricTreatment: false,
        familyPlanningServices: false,
        mortuaryServices: false,
        natalCare: false,
        dentalOptions: false,
        opticalOptions: false,
        diagnostics: false,
      },
      gender: "m",
      full_name: "",
      phone_num: "",
      individual_age: "",
      father_age: "",
      mother_age: "",
      grand_father_age: "",
      grand_mother_age: "",
      father_in_law_age: "",
      mother_in_law_age: "",
      spouse_age: "",
      child_1_age: "",
      child_2_age: "",
      child_3_age: "",
      child_4_age: "",
      child_5_age: "",
      child_6_age: "",
      child_7_age: "",
      child_8_age: "",
    },
  },
  compare: {
    fetching: false,
    plans: [],
    sort: {
      mode: "desc",
      icon: "sort-ascending",
      description: "Sort by price (most expensive first)",
    },
    bestPlan: {},
    cheapestPlan: {},
    mostExpensivePlan: {},
  },
  details: {
    email: "",
    price: 0,
    notGettingProviders: true,
    buyingPlan: false,
  },
};
