export const child_options = [
  { value: 0, label: "Select Age" },
  { value: 1, label: "1 Year" },
  { value: 2, label: "2 Years" },
  { value: 3, label: "3 Years" },
  { value: 4, label: "4 Years" },
  { value: 5, label: "5 Years" },
  { value: 6, label: "6 Years" },
  { value: 7, label: "7 Years" },
  { value: 8, label: "8 Years" },
  { value: 9, label: "9 Years" },
  { value: 10, label: "10 Years" },
  { value: 11, label: "11 Years" },
  { value: 12, label: "12 Years" },
  { value: 13, label: "13 Years" },
  { value: 14, label: "14 Years" },
  { value: 15, label: "15 Years" },
  { value: 16, label: "16 Years" },
  { value: 17, label: "17 Years" },
  { value: 18, label: "18 Years" },
];
